name: Continuous Integration

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    
    - name: Run a one-line script
      run: pwd
      
    - name: Prettify code check
      uses: creyD/prettier_action@v2.2
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md,ts,tsx,css} --ignore-path .prettierignore
        dry: true
        file_pattern: .
        prettier_version: 2.0.5
        

